// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"admin/index":{"path":"admin","id":"admin/index","parentId":"@@/global-layout"},"login/index":{"path":"login","id":"login/index","parentId":"@@/global-layout"},"list/index":{"path":"list","id":"list/index","parentId":"@@/global-layout"},"index":{"path":"/","id":"index","parentId":"@@/global-layout"},"docs":{"path":"docs","id":"docs","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'admin/index': React.lazy(() => import(/* webpackChunkName: "src__pages__admin__index" */'../../../src/pages/admin/index.tsx')),
'login/index': React.lazy(() => import(/* webpackChunkName: "src__pages__login__index" */'../../../src/pages/login/index.tsx')),
'list/index': React.lazy(() => import(/* webpackChunkName: "src__pages__list__index" */'../../../src/pages/list/index.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'docs': React.lazy(() => import(/* webpackChunkName: "src__pages__docs" */'../../../src/pages/docs.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/eleven/Desktop/构建/华信/front/umi4/src/layouts/index.tsx')),
},
  };
}
